### ISSUE TITLE
fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

### ISSUE THREAD

**Issue by adrianR2** [GregBowyer/cld2-cffi#7]
I get this error on installation attempt, on Windows 8.1, Python 2.7
`pip install cld2-cffi`

The full message is below

```
C:\Anaconda2\Lib\site-packages\textacy\textacy-0.2.2>pip install cld2-cffi
Collecting cld2-cffi
  Using cached cld2-cffi-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    _cffi_backend.c
    c/_cffi_backend.c(5600) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
    c/_cffi_backend.c(5601) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
    c/_cffi_backend.c(5602) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
    c/_cffi_backend.c(5603) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
    ffi.c
    c/libffi_msvc\ffi.c(122) : warning C4018: '>' : signed/unsigned mismatch
    prep_cif.c
    types.c
    win32.c
       Creating library build\temp.win32-2.7\Release\c\_cffi_backend.lib and object build\temp.win32-2.7\Release\c\_cffi_backend.exp

    Installed c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg
    running egg_info
    creating pip-egg-info\cld2_cffi.egg-info
    writing requirements to pip-egg-info\cld2_cffi.egg-info\requires.txt
    writing pip-egg-info\cld2_cffi.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\cld2_cffi.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\cld2_cffi.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\cld2_cffi.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    running build_ext
    building '_cffi__x2ee5b49exe62ada24' extension
    creating c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__pycache__\Release
    creating c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__pycache__\Release\cld2
    creating c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__pycache__\Release\cld2\__pycache__
    creating c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__pycache__\Release\cld2\internal
    C:\Users\Acer\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icld2\public -Icld2\internal -Icld2 -IC:\Ana
conda2\include -IC:\Anaconda2\PC /Tccld2\__pycache__\_cffi__x2ee5b49exe62ada24.c /Foc:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__pycache__\Release\cld2\__pyca
che__\_cffi__x2ee5b49exe62ada24.obj -O2
    _cffi__x2ee5b49exe62ada24.c
    C:\Users\Acer\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icld2\public -Icld2\internal -Icld2 -IC:\Ana
conda2\include -IC:\Anaconda2\PC /Tpcld2\encoding_lut.cc /Foc:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__pycache__\Release\cld2\encoding_lut.obj -O2
    encoding_lut.cc
    cld2\public\compact_lang_det.h(65) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\setup.py", line 189, in <module>
        'Topic :: Text Processing :: Linguistic'
      File "C:\Anaconda2\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\egg_info.py", line 186, in run
      File "C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\egg_info.py", line 209, in find_sources
      File "C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\egg_info.py", line 293, in run
      File "C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\egg_info.py", line 322, in add_defaults
      File "C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\sdist.py", line 120, in add_defaults
      File "C:\Anaconda2\lib\distutils\cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Anaconda2\lib\distutils\cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\build_py.py", line 33, in finalize_options
      File "C:\Anaconda2\lib\distutils\command\build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "C:\Anaconda2\lib\distutils\cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "C:\Anaconda2\lib\distutils\cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\setup.py", line 142, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\setup.py", line 127, in get_ext_modules
        import cld2
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\cld2\__init__.py", line 185, in <module>
        extra_compile_args=_COMPILER_ARGS)
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg\cffi\api.py", line 367, in verify
        lib = self.verifier.load_library()
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg\cffi\verifier.py", line 96, in load_library
        self._compile_module()
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg\cffi\verifier.py", line 192, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg\cffi\ffiplatform.py", line 28, in compile
        outputfilename = _build(tmpdir, ext)
      File "c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg\cffi\ffiplatform.py", line 54, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'C:\\Users\\Acer\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed wit
h exit status 2

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\acer\appdata\local\temp\pip-build-nbwof7\cld2-cffi\
```

Any suggestion? Thank you. Adrian

**Comment by GregBowyer** [comment]
This is MS not fully supporting C99 which includes `stdint.h`.

I will see if I can sort this out for you
